[theme]
primaryColor = "#E30613"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#222222"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
